apiVersion: v1
kind: Pod
metadata:
  name: log-generator
spec:
  containers:
    - name: log-generator
      image: alpine
      command:
        - sh
        - -c
        - while true; do echo $(date) Hello World!; sleep 1; done
  restartPolicy: Never
