apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ankit-info
  namespace: default
spec:
  secretName: ankit-info-tls-staging
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer  # This line tells cert-manager to use a ClusterIssuer
  dnsNames:
  - '*.DOMAIN_NAME'
  - DOMAIN_NAME
