#  Service to create a GCP load balancer
# If you need to override the default GCP load-balancer create by ingress-nginx

# apiVersion: v1
# kind: Service
# metadata:
#   labels:
#     app.kubernetes.io/component: controller
#     app.kubernetes.io/instance: ingress-nginx-ext
#     app.kubernetes.io/managed-by: Helm
#     app.kubernetes.io/name: ingress-nginx
#     app.kubernetes.io/part-of: ingress-nginx
#     app.kubernetes.io/version: 1.8.0
#     helm.sh/chart: ingress-nginx-4.7.0
#   name: ingress-nginx-ext-controller
#   namespace: ingress-nginx
# spec:
#   ipFamilies:
#   - IPv4
#   ipFamilyPolicy: SingleStack
#   ports:
#   - appProtocol: http
#     name: http
#     port: 80
#     protocol: TCP
#     targetPort: http
#   - appProtocol: https
#     name: https
#     port: 443
#     protocol: TCP
#     targetPort: https
#   selector:
#     app.kubernetes.io/component: controller
#     app.kubernetes.io/instance: ingress-nginx-ext
#     app.kubernetes.io/name: ingress-nginx
#   type: LoadBalancer