apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cert-manager

resources:
  - namespace.yaml  # Add your own resources here
  # - clusterIssuer-letsEncryptStaging.yaml
  # - certificate-letsEncryptStaging.yaml
  - clusterIssuer-letsEncryptProd.yaml
  - certificate-letsEncryptProd.yaml
  - ../../vendor/cert-manager


