apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ankit-info
  namespace: default
spec:
  secretName: ankit-info-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
  - '*.DOMAIN_NAME'
  - DOMAIN_NAME
